[package]
name = "demangle"
version = "0.1.0"
authors = ["vlakreeh <riverserver2012@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpp_demangle = "0.2.12"